### ISSUE TITLE
TonyTheTagger.py: 'getRoot' is not defined

### ISSUE THREAD

**Issue by jgoosey** [astar-security/Lestat#1]
```
[*] Assigning robustness
[*] Requesting wordlist...
[+] wordlist downloaded
Traceback (most recent call last):
  File ".\LesterTheLooter.py", line 611, in <module>
    main()
  File ".\LesterTheLooter.py", line 594, in main
    populateRobustness(cu, dom)
  File "C:\Users\gossj\cracking\Lestat\TonyTheTagger.py", line 108, in populateRobustness
    d2 = similar(None, user, getRoot(passw)).ratio()
NameError: name 'getRoot' is not defined
```

**Comment by jgoosey** [comment]
Commented out the "d2" line and the reference to in "elif d1 > 0.75" but breaks again in LesterTheLooter.py:

```
[+] wordlist downloaded
[*] Computing groups information
[*] Computing stats
Traceback (most recent call last):
  File ".\LesterTheLooter.py", line 611, in <module>
    main()
  File ".\LesterTheLooter.py", line 598, in main
    st = produceStats(users, cu)
  File ".\LesterTheLooter.py", line 554, in produceStats
    pat = sorted(statPattern(passwords, status).items(), key=lambda x: x[1], reverse=True)
  File ".\LesterTheLooter.py", line 469, in statPattern
    r = getRoot(p)
NameError: name 'getRoot' is not defined
```
